// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opanxrurytpgzshhkjkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wYW54cnVyeXRwZ3pzaGhramtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjA4NTUsImV4cCI6MjA3MTc5Njg1NX0.FfCVEQt7zVvXweR3XPoHpsJQRrlhjI5QikYW-KUUljc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});